all:
	pdflatex intro_gnu_linux
	pdflatex intro_gnu_linux
	pdflatex intro_gnu_linux

clean:
		rm -rf *.acn *.alg *.glg *.glo *.gls *.glsdefs *.ist *.xdy *.acr *.bbl *.blg *.aux *.dvi *.log *.lot *.idx *.toc *.lof *.brf *.out

mrproper: clean
		rm -rf *.pdf
